// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
	"MyCleanArchitecture/internal/infra/graph/model"
)

type Config struct {
	Resolvers ResolverRoot
}

type ResolverRoot interface {
	Mutation() MutationResolver
	Query() QueryResolver
}

type MutationResolver interface {
	CreateOrder(ctx context.Context, input model.OrderInput) (*model.Order, error)
}

type QueryResolver interface {
	Orders(ctx context.Context) ([]*model.Order, error)
}

func NewExecutableSchema(cfg Config) graphql.ExecutableSchema {
	// This is a simplified version for demonstration
	// In a real project, you would use gqlgen to generate this properly
	return nil
}
